//! Writes golden vectors for the WT video wire format (v2) to
//! `web/src/wtvideo.vectors.gen.ts`, so the browser client's decoder is checked
//! byte-for-byte against the Rust encoder (`wtvideo.rs` <-> `web/src/wtvideo.ts`).
//!
//! v2 is one frame per unidirectional stream, so a vector is simply a frame:
//! a 14-byte header and the access unit. The v1 vectors had to pin a
//! fragmenter, interleaved parity groups and a reassembly order - and, being
//! generated once and never re-run, they silently went stale and stopped
//! matching the code they existed to protect.
//!
//! Run from the repo root:
//!
//! ```sh
//! cargo run -p inphase-protocol --example dump_wtvideo_vectors
//! ```

use std::io::Write;
use std::path::PathBuf;

use inphase_protocol::WtFrame;

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

/// A deterministic, compressible-looking payload of `n` bytes.
fn payload(n: usize, seed: u8) -> Vec<u8> {
    (0..n)
        .map(|i| (i as u8).wrapping_mul(31).wrapping_add(seed))
        .collect()
}

fn main() -> std::io::Result<()> {
    let key = WtFrame {
        frame_no: 77,
        capture_us: 1_234_567_890,
        key: true,
        payload: payload(3000, 0x11),
    };
    let delta = WtFrame {
        frame_no: 78,
        capture_us: 1_234_584_557,
        key: false,
        payload: payload(600, 0x22),
    };
    let empty = WtFrame {
        frame_no: 79,
        capture_us: 1_234_601_224,
        key: false,
        payload: Vec::new(),
    };

    let mut out = String::new();
    out.push_str(
        "// Generated by crates/protocol/examples/dump_wtvideo_vectors.rs — do not edit.\n",
    );
    out.push_str("// Golden vectors pinning the WT video v2 wire format for `wtvideo.ts`.\n");
    out.push_str("export const WtVideoVectors = {\n");
    out.push_str(&format!(
        "  headerLen: {},\n",
        inphase_protocol::WT_VIDEO_HEADER_LEN
    ));
    out.push_str(&format!(
        "  version: {},\n",
        inphase_protocol::WT_VIDEO_PROTOCOL_VERSION
    ));
    out.push_str("  frames: [\n");
    for (name, f) in [("keyframe", &key), ("delta", &delta), ("empty", &empty)] {
        out.push_str("    {\n");
        out.push_str(&format!("      name: {name:?},\n"));
        out.push_str(&format!("      frameNo: {},\n", f.frame_no));
        out.push_str(&format!("      captureUs: \"{}\",\n", f.capture_us));
        out.push_str(&format!("      key: {},\n", f.key));
        out.push_str(&format!("      payloadHex: {:?},\n", hex(&f.payload)));
        out.push_str(&format!("      wireHex: {:?},\n", hex(&f.encode())));
        out.push_str("    },\n");
    }
    out.push_str("  ],\n");
    out.push_str("} as const;\n");

    let path = repo_root().join("web/src/wtvideo.vectors.gen.ts");
    let mut f = std::fs::File::create(&path)?;
    f.write_all(out.as_bytes())?;
    println!("wrote wtvideo v3 vectors to {}", path.display());
    Ok(())
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("crates/protocol/../..")
        .to_path_buf()
}
