// Asserts the TypeScript packet encoder matches the Rust host byte-for-byte,
// using the golden vectors generated by
// `cargo run -p inphase-protocol --example dump_vectors`
// (architecture report §19 Phase 3).

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import {
  encodePacket,
  toHex,
  InputKind,
  FLAG_UNADJUSTED_MOVEMENT,
  MOD_CTRL,
  MOD_SHIFT,
  type InputEvent,
} from "./protocol.js";

const vectorsPath = fileURLToPath(new URL("./protocol.vectors.json", import.meta.url));
const vectors = JSON.parse(readFileSync(vectorsPath, "utf8")) as { name: string; hex: string }[];

// Rebuild each named vector with the exact same inputs as `vectors.rs`.
const builders: Record<string, { seq: number; us: bigint; flags: number; ev: InputEvent }> = {
  mouse_move_unadjusted: {
    seq: 42,
    us: 1_234_567n,
    flags: FLAG_UNADJUSTED_MOVEMENT,
    ev: { kind: InputKind.MouseMove, dx: -3, dy: 7, wheelX: 0, wheelY: -1 },
  },
  mouse_buttons_left_right: {
    seq: 7,
    us: 0n,
    flags: 0,
    ev: { kind: InputKind.MouseButtons, buttons: 0b101 },
  },
  key_a_down_ctrl_shift: {
    seq: 1,
    us: 1n,
    flags: 0,
    ev: { kind: InputKind.Key, physicalCode: 0x1e, down: true, modifiers: MOD_CTRL | MOD_SHIFT },
  },
  gamepad_extremes: {
    seq: 100,
    us: 9_999_999n,
    flags: 0,
    ev: {
      kind: InputKind.Gamepad,
      state: { buttons: 0xdeadbeef, lx: -32768, ly: 32767, rx: 256, ry: -256, lt: 65535, rt: 0 },
    },
  },
  snapshot_empty: {
    seq: 0,
    us: 0n,
    flags: 0,
    ev: { kind: InputKind.Snapshot, state: { mouseButtons: 0, modifiers: 0, heldKeys: [] } },
  },
  snapshot_two_keys_with_gamepad: {
    seq: 55,
    us: 42n,
    flags: 0,
    ev: {
      kind: InputKind.Snapshot,
      state: {
        mouseButtons: 0b1,
        modifiers: MOD_SHIFT,
        heldKeys: [0x1e, 0x11],
        gamepad: { buttons: 1, lx: 1, ly: 2, rx: 3, ry: 4, lt: 5, rt: 6 },
      },
    },
  },
};

for (const v of vectors) {
  test(`golden vector: ${v.name}`, () => {
    const b = builders[v.name];
    assert.ok(b, `no TS builder for vector ${v.name}`);
    const bytes = encodePacket(b.seq, b.us, b.flags, b.ev);
    assert.equal(toHex(bytes), v.hex);
  });
}
