// Binary input packet v1 — byte-for-byte mirror of `crates/protocol/src/input.rs`
// (architecture report §12.2). Little-endian, 16-byte header + payload.
//
// The golden vectors in `protocol.vectors.json` (generated by
// `cargo run -p inphase-protocol --example dump_vectors`) are asserted by
// `protocol.test.ts` so this stays in sync with the host.

export const INPUT_PROTOCOL_VERSION = 1;
export const INPUT_HEADER_LEN = 16;

export const FLAG_UNADJUSTED_MOVEMENT = 0x0001;
export const FLAG_KEY_REPEAT = 0x0002;

export const MOD_SHIFT = 0x01;
export const MOD_CTRL = 0x02;
export const MOD_ALT = 0x04;
export const MOD_META = 0x08;

export const SNAP_GAMEPAD_PRESENT = 0x01;

export const enum InputKind {
  MouseMove = 1,
  MouseButtons = 2,
  Key = 3,
  Gamepad = 4,
  Snapshot = 5,
  Touch = 6,
}

export interface GamepadStateWire {
  buttons: number; // u32
  lx: number; ly: number; rx: number; ry: number; // i16
  lt: number; rt: number; // u16
}

export interface SnapshotStateWire {
  mouseButtons: number; // u16
  modifiers: number; // u8
  heldKeys: number[]; // u16[]
  gamepad?: GamepadStateWire;
}

export type InputEvent =
  | { kind: InputKind.MouseMove; dx: number; dy: number; wheelX: number; wheelY: number }
  | { kind: InputKind.MouseButtons; buttons: number }
  | { kind: InputKind.Key; physicalCode: number; down: boolean; modifiers: number }
  | { kind: InputKind.Gamepad; state: GamepadStateWire }
  | { kind: InputKind.Snapshot; state: SnapshotStateWire }
  | { kind: InputKind.Touch; pointerId: number; phase: number; x: number; y: number };

/** Monotonic per-connection sequence + client clock, injected by the encoder. */
export class InputEncoder {
  private seq = 0;
  private readonly t0 = performance.now();

  private nowUs(): bigint {
    return BigInt(Math.round((performance.now() - this.t0) * 1000));
  }

  encode(ev: InputEvent, flags = 0): Uint8Array {
    const seq = this.seq;
    this.seq = (this.seq + 1) >>> 0;
    return encodePacket(seq, this.nowUs(), flags, ev);
  }
}

export function encodePacket(
  sequence: number,
  clientMonotonicUs: bigint,
  flags: number,
  ev: InputEvent,
): Uint8Array {
  const body = payloadBytes(ev);
  const buf = new ArrayBuffer(INPUT_HEADER_LEN + body.length);
  const dv = new DataView(buf);
  dv.setUint8(0, INPUT_PROTOCOL_VERSION);
  dv.setUint8(1, ev.kind);
  dv.setUint16(2, flags, true);
  dv.setUint32(4, sequence >>> 0, true);
  dv.setBigUint64(8, clientMonotonicUs, true);
  new Uint8Array(buf).set(body, INPUT_HEADER_LEN);
  return new Uint8Array(buf);
}

function payloadBytes(ev: InputEvent): Uint8Array {
  const w = new Writer();
  switch (ev.kind) {
    case InputKind.MouseMove:
      w.i16(ev.dx); w.i16(ev.dy); w.i16(ev.wheelX); w.i16(ev.wheelY);
      break;
    case InputKind.MouseButtons:
      w.u16(ev.buttons);
      break;
    case InputKind.Key:
      w.u16(ev.physicalCode); w.u8(ev.down ? 1 : 0); w.u8(ev.modifiers);
      break;
    case InputKind.Gamepad:
      writeGamepad(w, ev.state);
      break;
    case InputKind.Snapshot: {
      const s = ev.state;
      w.u16(s.mouseButtons);
      w.u8(s.modifiers);
      w.u8(s.gamepad ? SNAP_GAMEPAD_PRESENT : 0);
      w.u16(s.heldKeys.length);
      for (const k of s.heldKeys) w.u16(k);
      if (s.gamepad) writeGamepad(w, s.gamepad);
      break;
    }
    case InputKind.Touch:
      w.u32(ev.pointerId); w.u8(ev.phase); w.u8(0); w.u16(ev.x); w.u16(ev.y);
      break;
  }
  return w.bytes();
}

function writeGamepad(w: Writer, g: GamepadStateWire) {
  w.u32(g.buttons);
  w.i16(g.lx); w.i16(g.ly); w.i16(g.rx); w.i16(g.ry);
  w.u16(g.lt); w.u16(g.rt);
}

class Writer {
  private parts: number[] = [];
  u8(v: number) { this.parts.push(v & 0xff); }
  u16(v: number) { v &= 0xffff; this.parts.push(v & 0xff, (v >>> 8) & 0xff); }
  i16(v: number) { this.u16(v < 0 ? v + 0x10000 : v); }
  u32(v: number) {
    v >>>= 0;
    this.parts.push(v & 0xff, (v >>> 8) & 0xff, (v >>> 16) & 0xff, (v >>> 24) & 0xff);
  }
  bytes(): Uint8Array { return Uint8Array.from(this.parts); }
}

export function toHex(b: Uint8Array): string {
  return Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");
}
