import {
  createElement,
  Monitor,
  Settings2,
  ArrowUpRight,
  Search,
  ShieldCheck,
  Copy,
  RefreshCw,
  Smartphone,
  Activity,
  ChevronRight,
  X,
  Wifi,
  WifiOff,
  CircleHelp,
  LogOut,
  Link,
  Gamepad2,
  Play,
  Keyboard,
  Maximize,
  Ellipsis,
  Power,
  QrCode,
  Check,
  TriangleAlert,
} from "lucide";
const icons = {
  monitor: Monitor,
  settings: Settings2,
  arrow: ArrowUpRight,
  search: Search,
  shield: ShieldCheck,
  copy: Copy,
  refresh: RefreshCw,
  device: Smartphone,
  activity: Activity,
  chevron: ChevronRight,
  close: X,
  wifi: Wifi,
  wifiOff: WifiOff,
  help: CircleHelp,
  logout: LogOut,
  link: Link,
  gamepad: Gamepad2,
  play: Play,
  keyboard: Keyboard,
  maximize: Maximize,
  more: Ellipsis,
  power: Power,
  qr: QrCode,
  check: Check,
  alert: TriangleAlert,
};
export type IconName = keyof typeof icons;
export function icon(name: IconName, size = 20): string {
  return createElement(icons[name], {
    width: size,
    height: size,
    "stroke-width": 1.7,
    "aria-hidden": "true",
    focusable: "false",
  }).outerHTML;
}
