// Captured from a live host by crates/host/examples/wt_probe.rs — the
// order frames actually complete on the wire, including the stale frames
// a previous pipeline was still delivering when the session started.
export const RealArrivals: ReadonlyArray<{ n: number; key: boolean }> = [
  { n: 685, key: false },
  { n: 684, key: false },
  { n: 686, key: false },
  { n: 687, key: false },
  { n: 0, key: true },
  { n: 1, key: false },
  { n: 2, key: false },
  { n: 3, key: false },
  { n: 4, key: false },
  { n: 5, key: false },
  { n: 6, key: false },
  { n: 7, key: false },
  { n: 8, key: false },
  { n: 9, key: false },
  { n: 10, key: false },
  { n: 11, key: false },
  { n: 12, key: false },
  { n: 13, key: false },
  { n: 14, key: false },
  { n: 15, key: false },
  { n: 16, key: false },
  { n: 17, key: false },
  { n: 18, key: false },
  { n: 19, key: false },
  { n: 20, key: false },
  { n: 21, key: false },
  { n: 22, key: false },
  { n: 24, key: false },
  { n: 23, key: false },
  { n: 25, key: false },
  { n: 26, key: false },
  { n: 27, key: false },
  { n: 28, key: false },
  { n: 29, key: false },
  { n: 30, key: false },
  { n: 31, key: false },
  { n: 32, key: false },
  { n: 33, key: false },
  { n: 34, key: false },
  { n: 35, key: false },
];
