// Byte-for-byte compatibility tests for the WT video wire-format mirror
// (`wtvideo.ts`) against vectors generated by the Rust implementation
// (`cargo run -p inphase-protocol --example dump_wtvideo_vectors`).
//
// v2 is one frame per unidirectional stream, so a vector is just a frame. The
// v1 vectors had to pin a fragmenter, interleaved parity groups and an ingest
// order - and, being generated once and never regenerated, they went stale and
// stopped describing the code they existed to protect. These are small enough
// to regenerate on any wire change.
import assert from "node:assert/strict";
import test from "node:test";

import { WtVideoVectors as vectors } from "./wtvideo.vectors.gen.js";
import { parseFrame, WT_VIDEO_HEADER_LEN, WT_VIDEO_PROTOCOL_VERSION } from "./wtvideo.js";

function hexToBytes(h: string): Uint8Array {
  const out = new Uint8Array(h.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(h.slice(i * 2, i * 2 + 2), 16);
  return out;
}
function bytesToHex(b: Uint8Array): string {
  return Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");
}

test("the mirror agrees with Rust on the header shape", () => {
  assert.equal(WT_VIDEO_HEADER_LEN, vectors.headerLen);
  assert.equal(WT_VIDEO_PROTOCOL_VERSION, vectors.version);
});

for (const v of vectors.frames) {
  test(`golden frame: ${v.name}`, () => {
    const frame = parseFrame(hexToBytes(v.wireHex));
    assert.ok(frame, "vector parses");
    assert.equal(frame.frame_no, v.frameNo);
    assert.equal(frame.capture_us, Number(v.captureUs));
    assert.equal(frame.key, v.key);
    assert.equal(bytesToHex(frame.payload), v.payloadHex);
  });
}

test("a truncated stream body is rejected, not half-parsed", () => {
  const full = hexToBytes(vectors.frames[0]!.wireHex);
  assert.equal(parseFrame(full.subarray(0, WT_VIDEO_HEADER_LEN - 1)), null);
  assert.equal(parseFrame(new Uint8Array(0)), null);
});

test("the v1 datagram format is refused rather than misread", () => {
  const wire = hexToBytes(vectors.frames[0]!.wireHex);
  wire.set([1], 0); // v1
  assert.equal(parseFrame(wire), null);
});

test("unknown flag bits are ignored", () => {
  const key = vectors.frames.find((f) => f.key);
  assert.ok(key, "a keyframe vector exists");
  const wire = hexToBytes(key.wireHex);
  wire.set([(wire[1] ?? 0) | 0x80], 1);
  assert.equal(parseFrame(wire)?.key, true);
});

test("a frame of any size is one buffer - there is no fragment count", () => {
  // The v1 failure mode: a 1440p keyframe became ~300 datagrams and a single
  // loss discarded the frame. v3 declares the size in the header instead of
  // implying it from EOF; the length is only checked for consistency with the
  // body, never capped.
  const big = new Uint8Array(WT_VIDEO_HEADER_LEN + 2_000_000);
  big.set([WT_VIDEO_PROTOCOL_VERSION, 0x01], 0);
  new DataView(big.buffer).setUint32(14, 2_000_000, true);
  const frame = parseFrame(big);
  assert.ok(frame);
  assert.equal(frame.payload.byteLength, 2_000_000);
  assert.equal(frame.key, true);
});
